### ISSUE TITLE
BUG: MUT file headers no longer read in IGV, error:column 2 must be numeric

### ISSUE THREAD

**Issue by ctcncgr** [igvteam/igv#213]
This was not a problem in the previous versions of IGV, I believe this was introduced with the newly added indexing ability of IGV (which is great btw thank you).

My IGV version is 2.3.69.

What I did to produce this error was attempt to index, or load, a MUT file that I had created       
previously (and loaded previously into IGV) with the header essentially mirroring that described    
by the document here:
https://www.broadinstitute.org/software/igv/sites/cancerinformatics.org.igv/files/linked_files/example.mut

I expected IGVtools and IGV to index and load, respectively, the MUT file I provided.

What happens is that I receive an error about column 2 not being numeric, on both load into IGV and index using IGVtools:

"an error occured while accessing:mut_out.mut<br>Column 2 must be numeric value"

If i remove the header, or comment it with '#', the error goes away, but the on-hover display information about the mutation in question is prefaced with the wrong identifiers (really the first line in my MUT file is read as the header, because I cannot provide an actual header, because column 2 must be numeric).

Thank you,

Connor

**Comment by jrobinso** [comment]
Hi, this has been fixed,  is this a new report?

**Comment by ctcncgr** [comment]
OH thank you

I didnt see any response to it no the IGV user groups this is a new post

**Comment by jrobinso** [comment]
OK, do a pull and try it again, or try 2.3.70.   Note that the windows 
package on the downloads page hasn't been updated yet, all the other 
links should point to 2.3.70.

Jim

**Comment by ctcncgr** [comment]
hey jim,

I just tried the 2.3.70 version after downloading IGVTools again.  I still get the same error.

Am I doing something wrong?

I am running:

java -jar igvtools.jar index mut_out.mut

I asked for the version and it gave me 2.3.70

Thank you,

Connor

**Comment by jrobinso** [comment]
Apologies, there is a flaw in the fix I pushed.   Will get a better fix 
pushed later today.

**Comment by ctcncgr** [comment]
No worries.  Thank you so much for the rapid response and all your work on this.  I really appreciate your help.

**Comment by jrobinso** [comment]
There's a deeper flaw in the htsjdk library I'm using to index, it 
doesn't support a fixed length header (i.e. header not starting with a 
specific string).   I'm trying to work around it without hacking htsjdk.

**Comment by jrobinso** [comment]
Just updated the releases to 2.3.71 with better fix.
