### ISSUE TITLE
merge=true is buggy when using custome genome

### ISSUE THREAD

**Issue by serine** [igvteam/igv#339]
Hi there, 

I wasn't sure if that was a bug and I asked a question at [igv-help forum](https://groups.google.com/forum/#!topic/igv-help/bBpWEtWos_A). Apparently this is a bug.

Basicaly when I make my own `.genome` file and include that file into URLs, sessions don't get merged.

```
[bioinformatics-platform2]:project_may_2016/GCF_000156855.2_ASM15685v2% ls -1
GCF_000156855.2_ASM15685v2.genome
GCF_000156855.2_ASM15685v2_genomic.fna
GCF_000156855.2_ASM15685v2_genomic.fna.fai
GCF_000156855.2_ASM15685v2_genomic.gff
property.txt
```

```
[bioinformatics-platform2]:project_may_2016/GCF_000156855.2_ASM15685v2% cat property.txt 
fasta=true
fastaDirectory=false
ordered=true
id=GCF_000156855.2_ASM15685v2
name=gonorrhoeae
geneFile=GCF_000156855.2_ASM15685v2_genomic.gff
sequenceLocation=GCF_000156855.2_ASM15685v2_genomic.fna
```

I include this custome genome like this 

```
<a href='http://localhost:60151/load?genome=http%3A%2F%2Fbioinformatics.erc.monash.edu%2Fhome%2Fkirill%2Fprojects%2Fproject_may_2016%2FGCF_000156855.2_ASM15685v2%2FGCF_000156855.2_ASM15685v2.genome'>Load genome</a>
```

Everything works fine and genome is loaded, but if genome is attached to a bam file (every BAM file URL has `genome=value` attribute) then IGV session gets overwritten. However If i just load the genome with URL shown above. I then can load BAM file all into the same session, by excluding `genome=value` attribute

Thanks

**Comment by jrobinso** [comment]
This is fixed. The fix should appear in the nightly development snapshot, and the next point release.  ETA by the end of the month.

**Comment by serine** [comment]
@jrobinso where do I get nightly snapshot, is it just master branch? also what does ETA stands for? and will that be in releases? 

Going to grab master branch now and test it out

Thanks

**Comment by jrobinso** [comment]
Look on the downloads page,  there is a link to the snapshot.   Also,  ETA
stands for "Estimated Time of Arrival",  I think, but in this case means
estimated time of release.

The release with this fix will go out tomorrow or Thursday,  numbered
2.3.89.   In the meantime the snapshot build should work:
http://software.broadinstitute.org/software/igv/download_snapshot

**Comment by serine** [comment]
ok thanks. just tested master branch, still the same, session don't get merged. Going to try out snapshot. Just out of interest snapshot comes from master branch?

**Comment by serine** [comment]
nope, sorry, snapshot doesn't work either

**Comment by serine** [comment]
If it helps here is log of what is going on if I lanch from cmd

```
WARN [2016-12-21 13:32:34,373]  [Globals.java:152] [main]  Development mode is enabled
WARN [2016-12-21 13:32:34,373] [Globals.java:152]  Development mode is enabled
INFO [2016-12-21 13:32:34,375]  [DirectoryManager.java:167] [main]  IGV Directory: /home/kirill/igv
INFO [2016-12-21 13:32:34,375] [DirectoryManager.java:167]  IGV Directory: /home/kirill/igv
INFO [2016-12-21 13:32:34,377]  [Main.java:136] [main]  Startup  IGV Version Snapshot (824 (824))12/20/2016 04:38 AM
INFO [2016-12-21 13:32:34,377]  [Main.java:137] [main]  Java 1.8.0_111
INFO [2016-12-21 13:32:34,377]  [DirectoryManager.java:72] [main]  Fetching user directory... 
INFO [2016-12-21 13:32:34,487]  [Main.java:138] [main]  Default User Directory: /home/kirill
INFO [2016-12-21 13:32:34,487]  [Main.java:139] [main]  OS: Linux
INFO [2016-12-21 13:32:35,511]  [IGVCommandBar.java:307] [main]  Loading CP008706.1  Acenitobacter_baumannii_AB5075-UW-1_sRNA (CP008706.1)   http://bioinformatics.erc.monash.edu/home/kirill/projects/blah/blah-remapping-with-mouse-genome.17.11.2016/refFiles/ABUW5075_with_extras.gbk
INFO [2016-12-21 13:32:35,710]  [GenomeManager.java:145] [main]  Loading genome: http://bioinformatics.erc.monash.edu/home/kirill/projects/blah/blah-remapping-with-mouse-genome.17.11.2016/refFiles/ABUW5075_with_extras.gbk
INFO [2016-12-21 13:32:36,575]  [GenomeManager.java:192] [main]  Genome loaded.  id= CP008706.1
INFO [2016-12-21 13:32:36,780]  [CommandListener.java:106] [Thread-7]  Listening on port 60151
INFO [2016-12-21 13:32:42,041]  [CommandListener.java:167] [Thread-7]  GET /load?file=http%3A%2F%2Fbioinformatics.erc.monash.edu%2Fhome%2Fkirill%2Fprojects%2Fblah%2Fblah-remapping-with-mouse-genome.17.11.2016%2FbamFiles%2Fvivo1_sorted.bam&genome=http%3A%2F%2Fbioinformatics.erc.monash.edu%2Fhome%2Fkirill%2Fprojects%2Fblah%2Fblah-remapping-with-mouse-genome.17.11.2016%2FrefFiles%2FABUW5075_with_extras.gbk&merge=true&name=vivo1 HTTP/1.1
INFO [2016-12-21 13:32:42,414]  [GenomeManager.java:145] [Thread-7]  Loading genome: http://bioinformatics.erc.monash.edu/home/kirill/projects/blah/blah-remapping-with-mouse-genome.17.11.2016/refFiles/ABUW5075_with_extras.gbk
INFO [2016-12-21 13:32:43,001]  [GenomeManager.java:192] [Thread-7]  Genome loaded.  id= CP008706.1
INFO [2016-12-21 13:32:43,004]  [IGVCommandBar.java:307] [Thread-7]  Loading CP008706.1  Acenitobacter_baumannii_AB5075-UW-1_sRNA (CP008706.1)   http://bioinformatics.erc.monash.edu/home/kirill/projects/blah/blah-remapping-with-mouse-genome.17.11.2016/refFiles/ABUW5075_with_extras.gbk
INFO [2016-12-21 13:32:43,004]  [IGVCommandBar.java:307] [Thread-7]  Loading CP008706.1  Acenitobacter_baumannii_AB5075-UW-1_sRNA (CP008706.1)   http://bioinformatics.erc.monash.edu/home/kirill/projects/blah/blah-remapping-with-mouse-genome.17.11.2016/refFiles/ABUW5075_with_extras.gbk
INFO [2016-12-21 13:32:43,006]  [IGV.java:1721] [Thread-7]  Loading 1 resources.
INFO [2016-12-21 13:32:43,007]  [TrackLoader.java:126] [Thread-7]  Loading resource, path http://bioinformatics.erc.monash.edu/home/kirill/projects/blah/blah-remapping-with-mouse-genome.17.11.2016/bamFiles/vivo1_sorted.bam
INFO [2016-12-21 13:32:43,037]  [HttpUtils.java:838] [Thread-7]  Range-byte request succeeded
INFO [2016-12-21 13:33:02,180]  [CommandListener.java:167] [Thread-7]  GET /load?file=http%3A%2F%2Fbioinformatics.erc.monash.edu%2Fhome%2Fkirill%2Fprojects%2Fblah%2Fblah-remapping-with-mouse-genome.17.11.2016%2FbamFiles%2Fvivo2_sorted.bam&genome=http%3A%2F%2Fbioinformatics.erc.monash.edu%2Fhome%2Fkirill%2Fprojects%2Fblah%2Fblah-remapping-with-mouse-genome.17.11.2016%2FrefFiles%2FABUW5075_with_extras.gbk&merge=true&name=vivo2 HTTP/1.1
INFO [2016-12-21 13:33:07,603]  [GenomeManager.java:145] [Thread-7]  Loading genome: http://bioinformatics.erc.monash.edu/home/kirill/projects/blah/blah-remapping-with-mouse-genome.17.11.2016/refFiles/ABUW5075_with_extras.gbk
INFO [2016-12-21 13:33:09,402]  [GenomeManager.java:192] [Thread-7]  Genome loaded.  id= CP008706.1
INFO [2016-12-21 13:33:09,404]  [IGVCommandBar.java:307] [Thread-7]  Loading CP008706.1  Acenitobacter_baumannii_AB5075-UW-1_sRNA (CP008706.1)   http://bioinformatics.erc.monash.edu/home/kirill/projects/blah/blah-remapping-with-mouse-genome.17.11.2016/refFiles/ABUW5075_with_extras.gbk
INFO [2016-12-21 13:33:09,405]  [IGVCommandBar.java:307] [Thread-7]  Loading CP008706.1  Acenitobacter_baumannii_AB5075-UW-1_sRNA (CP008706.1)   http://bioinformatics.erc.monash.edu/home/kirill/projects/blah/blah-remapping-with-mouse-genome.17.11.2016/refFiles/ABUW5075_with_extras.gbk
INFO [2016-12-21 13:33:09,405]  [IGV.java:1721] [Thread-7]  Loading 1 resources.
INFO [2016-12-21 13:33:09,406]  [TrackLoader.java:126] [Thread-7]  Loading resource, path http://bioinformatics.erc.monash.edu/home/kirill/projects/blah/blah-remapping-with-mouse-genome.17.11.2016/bamFiles/vivo2_sorted.bam
```
I've masked couple of variables since this is someelse data

**Comment by jrobinso** [comment]
Can I see your session file?  You don't actually have to specify the genome
in the link, that can be set in the session.   The underlying issue is IGV
thinks this is a new genome, i.e. not the genome currently loaded.   It
might be making that mistake from the session file.

If you could setup a test situation with public urls that reproduces the
situation that might help.   In the meantime send me your session file and
I'll see if I can simulate it.   Its getting late now to make the 2.3.89
release.

**Comment by serine** [comment]
I don't worry which release its gonna be in, as long as it fixed. I don't have this problem if I specify inbuild genome e.g genome=mm10. Where is that session file? is it this log file `/home/kirill/.igv/igv/igv.log` 

If so I can't send it to you cause it has full path to file and users. I'll set up public test links

**Comment by jrobinso** [comment]
Sorry, you said "session file"  so I assumed you were generating IGV
session files.   Are you not?    If you aren't sure what a session file is
look at this:  http://software.broadinstitute.org/software/igv/Sessions

Could you post one of your links that includes a bam  a bam file?   I
looked back through this thread and only see a post loading a genome file.
Apologies if I missed it.

**Comment by serine** [comment]
Right, no I not generating igv sessions. I'm simply making URL links

Here is two link to public data

http://bioinformatics.erc.monash.edu/home/kirill/igvTest/inbuilt.html
http://bioinformatics.erc.monash.edu/home/kirill/igvTest/other.html

basically `inbuilt.html` uses genome=mm10, which works fine, but sometime I need different genome to be loaded with annotation. And in `other.html` I made custom `.genome` file

```
[bioinformatics-platform2]:www/igvTest% cat refFiles/t/property.txt 
fasta=true
id=mm10-other
name=Mouse (mm10-other)
geneFile=http://bioinformatics.erc.monash.edu/home/kirill/igvTest/refFiles/Mus_musculus.GRCm38.84.gtf
geneTrackName=Ensembl
sequenceLocation=http://bioinformatics.erc.monash.edu/home/kirill/igvTest/refFiles/Mus_musculus.GRCm38.dna_sm.primary_assembly.fa
```

but for some reason this isn't working at all right now. I though I worked before, but didn't merge the sessions

**Comment by serine** [comment]
here is another link

http://bioinformatics.erc.monash.edu/home/kirill/igvTest/fasta.html

this one has `genome=http://bioinformatics.erc.monash.edu/home/kirill/igvTest/refFiles/Mus_musculus.GRCm38.dna_sm.primary_assembly.fa` and in this one, using sanpshot, session do merge. But how do you get the annotation in e.g GTF file

**Comment by jrobinso** [comment]
Ok,  I'll look at these tomorrow.  I was thrown totally of track by the
"session" reference,  the merge parameter was introduced for sessions.

**Comment by serine** [comment]
thanks, if you reckon that session is better to go about this I certainly can use that instead. I do like the idea of JSON, maybe I can just wait for that. Being able to merge is important but not crutial for me right now.

**Comment by jrobinso** [comment]
I can't reproduce your problem using the test page you provided:
http://bioinformatics.erc.monash.edu/home/kirill/igvTest/fasta.html

I can't launch IGV with the link, get a 404.  However, after launching
manually I can click the first load link, followed by the second.  Merge
works correctly (see screenshot).    How are you launching IGV?  If you are
using your own jnlp that could be the problem.    Use "Help > About" to
confirm you are running the latest version or latest build if using the
snapshot.
